#include "trc_io.h"
#include <QFile>
#include <QTextStream>
#include <QDateTime>
#include <QDate>
#include <QRegularExpression>
#include <cstring>
#include <cmath>

namespace socketspy::gui {

// ---------------------------------------------------------------------------
// Julian day helper — days since 1899-12-30 (OLE Automation date epoch)
// ---------------------------------------------------------------------------

static double oleAutomationDate() {
    // Reference: 1899-12-30 00:00:00 UTC
    static const QDate kOleEpoch(1899, 12, 30);
    const QDateTime now = QDateTime::currentDateTimeUtc();
    const double days = static_cast<double>(kOleEpoch.daysTo(now.date()));
    const double frac = (now.time().msecsSinceStartOfDay() / 86400000.0);
    return days + frac;
}

// ---------------------------------------------------------------------------
// TrcWriter::write
// ---------------------------------------------------------------------------

bool TrcWriter::write(const QList<socketspy::core::CanFrame>& frames,
                      const QString& path)
{
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate | QIODevice::Text))
        return false;

    QTextStream out(&f);
    const double startTime = oleAutomationDate();
    const QDateTime now = QDateTime::currentDateTime();

    // --- Header ---
    out << ";$FILEVERSION=2.0\n";
    out << QString(";$STARTTIME=%1\n").arg(startTime, 0, 'f', 6);
    out << ";\n";
    out << QString(";   Start time: %1\n")
            .arg(now.toString("dd.MM.yyyy hh:mm:ss.zzz"));
    out << ";   Generated by SocketSpy\n";
    out << ";-------------------------------------------------------------------------------\n";
    out << ";   Message   Time    Type ID     Rx/Tx\n";
    out << ";   Number    [ms]          [hex]       DLC Data [hex] ...\n";
    out << ";-------------------------------------------------------------------------------\n";

    // Baseline timestamp for relative time
    const uint64_t baseUs = frames.isEmpty() ? 0 : frames.first().timestamp_us;

    int n = 1;
    for (const auto& frame : frames) {
        const double timeMs = static_cast<double>(frame.timestamp_us - baseUs) / 1000.0;
        const uint8_t dlc = std::min(frame.dlc, static_cast<uint8_t>(64));

        QString dataHex;
        for (int i = 0; i < static_cast<int>(dlc); ++i) {
            if (i > 0) dataHex += ' ';
            dataHex += QString("%1").arg(frame.data[i], 2, 16, QChar('0')).toUpper();
        }

        // Format: %7d)  %10.3f DT  %08X Rx  %2d  %s
        out << QString("%1)  %2 DT  %3 Rx  %4  %5\n")
                .arg(n, 7)
                .arg(timeMs, 10, 'f', 3)
                .arg(frame.id, 8, 16, QChar('0')).toUpper()
                .arg(dlc, 2)
                .arg(dataHex);
        ++n;
    }

    f.close();
    return true;
}

// ---------------------------------------------------------------------------
// TrcReader::read
// ---------------------------------------------------------------------------

QList<socketspy::core::CanFrame> TrcReader::read(const QString& path)
{
    QList<socketspy::core::CanFrame> frames;
    QFile f(path);
    if (!f.open(QIODevice::ReadOnly | QIODevice::Text))
        return frames;

    QTextStream in(&f);
    // Pattern: N)  T DT  ID Rx DLC BYTES...
    // Example: "      1)       0.000 DT  0CF00400 Rx   8  F0 1C 00 FF FF FF 00 FF"
    static const QRegularExpression re(
        R"(^\s*\d+\)\s+([\d.]+)\s+DT\s+([0-9A-Fa-f]+)\s+(?:Rx|Tx)\s+(\d+)\s*((?:[0-9A-Fa-f]{2}\s*)*))");

    while (!in.atEnd()) {
        const QString line = in.readLine();
        if (line.trimmed().isEmpty() || line.trimmed().startsWith(';'))
            continue;

        const auto m = re.match(line);
        if (!m.hasMatch()) continue;

        socketspy::core::CanFrame frame{};
        const double timeMs = m.captured(1).toDouble();
        frame.timestamp_us = static_cast<uint64_t>(timeMs * 1000.0);
        frame.id  = m.captured(2).toUInt(nullptr, 16);
        frame.dlc = static_cast<uint8_t>(m.captured(3).toUInt());

        const QString hexData = m.captured(4).simplified();
        if (!hexData.isEmpty()) {
            const QStringList bytes = hexData.split(' ');
            const int count = std::min(static_cast<int>(bytes.size()),
                                       static_cast<int>(frame.dlc));
            for (int i = 0; i < count; ++i)
                frame.data[i] = static_cast<uint8_t>(bytes[i].toUInt(nullptr, 16));
        }
        frames.append(frame);
    }
    return frames;
}

} // namespace socketspy::gui
